volumes:
  excalidraw:
    driver: local
    driver_opts:
      type: none
      device: /volume/excalidraw/data
      o: bind

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    profiles:
      - tools
    ports:
      - 80:80
    networks:
      - dev-net
    volumes:
      - excalidraw:/excalidraw
    # environment:
    #   - EXCALIDRAW_BASE_URL=http://localhost:3000
    #   - EXCALIDRAW_PORT=3000
    #   - EXCALIDRAW_HOST=localhost
